spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: account-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
server:
  port: 3030
